### PR TITLE
Update to 9.014.01

### PR DESCRIPTION
**Pull request by alper-han**
.

### CODE REVIEW

**Comment by notpeelz** [comment]
Thanks

**Comment by notpeelz** [comment]
Is the `Update r8125_n.c -- FIX EEE (BUILD PROBLEM)` commit still necessary with 9.014.01? I'd rather not add extra changes, as this repo is just a mirror.

**Comment by alper-han** [comment]
As of version “9.014.01” it seems to be unnecessary.
I did the necessary tests and was able to compile without any problems.

https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/os-specific/linux/r8125/default.nix
I copied the configuration from

version = “9.014.01”;
sha256 = “sha256-vYgAOmKFQZDKrZsS3ynXB0DrT3wU0JWzNTYO6FyMG9M=”

I modified it to be.

“export NIXPKGS_ALLOW_BROKEN=1”
I entered the command in the terminal to compile the broken packages

nix-build -E 'let pkgs = import <nixpkgs> { config = {}; }; in pkgs.callPackage ./default.nix { kernel = pkgs.linuxPackages.kernel; }'
nix-build -E 'let pkgs = import <nixpkgs> { config = {}; }; in pkgs.callPackage ./default.nix { kernel = pkgs.linuxPackages_5_10.kernel; }'
nix-build -E 'let pkgs = import <nixpkgs> { config = {}; }; in pkgs.callPackage ./default.nix { kernel = pkgs.linuxPackages_6_11.kernel; }'
nix-build -E 'let pkgs = import <nixpkgs> { config = {}; }; in pkgs.callPackage ./default.nix { kernel = pkgs.linuxPackages_latest.kernel; }'
nix-build -E 'let pkgs = import <nixpkgs> { config = {}; }; in pkgs.callPackage ./default.nix { kernel = pkgs.linuxPackages_zen.kernel; }'


There is no problem.
The package is not broken now.

Can you run the necessary tests yourself?
Can you take the necessary action to remove the broken mark from the package?

**Comment by notpeelz** [comment]
Unfortunately I don't use NixOS anymore.

**Pull request closed without merging**
